[platformio]
default_envs = sensor_node

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

[env:i2c_scanner]
build_src_filter =
    -<*>
    +<i2c_scanner.cpp>

[env:sensor_node]
build_src_filter =
    -<*>
    +<sensor_node.cpp>
lib_deps =
    adafruit/Adafruit AHTX0
    adafruit/ENS160 - Adafruit Fork
    adafruit/Adafruit MLX90614 Library
    adafruit/Adafruit MPU6050
    adafruit/DHT sensor library
    knolleary/PubSubClient
